- name: Install and configure Nagios
  block:
    - name: Install Nagios core and plugins
      apt:
        name:
          - nagios4
          - nagios-plugins-contrib
          - nagios-nrpe-plugin
        state: present
        update_cache: yes

    - name: Copy hosts config file
      copy:
        src: hosts.cfg
        dest: /etc/nagios4/conf.d/hosts.cfg
        mode: '0644'

    - name: Replace default contacts config file
      copy:
        src: contacts.cfg
        dest: /etc/nagios4/objects/contacts.cfg
        mode: '0644'

    - name: Replace default CGI config file
      copy:
        src: cgi.cfg
        dest: /etc/nagios4/cgi.cfg
        mode: '0644'

  notify:
    - Reload nagios

- name: Configure Apache
  block:
    - name: Copy authenticated users file
      copy:
        src: htdigest.users
        dest: /etc/nagios4/htdigest.users
        mode: '0640'

    - name: Enable CGI authentication
      lineinfile:
        path: /etc/nagios4/cgi.cfg
        regexp: '^use_authentication=0'
        line: 'use_authentication=1'
        backrefs: yes

    - name: Copy Apache conf file
      copy:
        src: nagios4.conf
        dest: /etc/apache2/sites-available/nagios4.conf
        mode: '0644'

    - name: Enable the nagios site
      command:
        cmd: a2ensite nagios4.conf

    - name: Enable CGI module
      command:
        cmd: a2enmod cgi
  notify:
    - Restart apache
