- name: Install and configure Nagios
  block:
    - name: Install Nagios core and plugins
      apt:
        name:
          - nagios4
          - nagios-plugins-contrib
          - nagios-nrpe-plugin
        state: present
        update_cache: yes

    - name: Copy custom Nagios configuration files
      copy:
        src: "{{ item }}"
        dest: "/etc/nagios4/conf.d/{{ item | basename | regex_replace('\\.j2$', '') }}"
        mode: '0644'
      loop:
        - hosts.cfg

    - name: Replace default Nagios configuration files
      copy:
        src: "{{ item }}"
        dest: "/etc/nagios4/objects/{{ item | basename | regex_replace('\\.j2$', '') }}"
        mode: '0644'
      loop:
        - contacts.cfg
  notify:
    - Reload nagios

- name: Configure Apache
  block:
    - name: Copy authenticated users file
      copy:
        src: htdigest.users
        dest: /etc/nagios4/htdigest.users
        mode: '0640'

    - name: Enable CGI authentication
      lineinfile:
        path: /etc/nagios4/cgi.cfg
        regexp: '^use_authentication=0'
        line: 'use_authentication=1'
        backrefs: yes

    - name: Copy Apache conf file
      copy:
        src: nagios4.conf
        dest: /etc/apache2/sites-available/nagios4.conf
        mode: '0644'

    - name: Enable the nagios site
      command:
        cmd: a2ensite nagios4.conf
  notify:
    - Reload apache
