- name: Install Nagios with plugins
  apt:
    name:
      - nagios4
      - nagios-plugins-contrib
      - nagios-nrpe-plugin
    state: present
    update_cache: yes

- name: Copy Nagios configuration files
  template:
    src: "{{ item }}"
    dest: "/etc/nagios4/conf.d/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: '0644'
  loop:
    - nagios.cfg.j2
    - hosts.cfg.j2
  notify: Restart nagios
