# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  become: true
  hosts: all
  roles:
    - common

- name: configure and deploy the webservers
  become: true
  hosts: webservers
  roles:
    - webserver

- name: configure and deploy the load balancer
  become: true
  hosts: loadbalancer
  roles:
    - loadbalancer
