# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: configure and deploy the webservers
  hosts: webservers
  roles:
    - webserver
