- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Deploy HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart haproxy

- name: Run the HAProxy service
  service:
    name: haproxy
    state: started
    enabled: yes
