- name: Allow SSH for users and Ansible from Nagios server to others
  when:
    - inventory_hostname in groups['webservers'] or
      inventory_hostname in groups['loadbalancer']
  ufw:
    rule: allow
    from_ip: 35.95.66.224
    to_port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 2222

- name: Deny all other SSH
  when:
    - inventory_hostname in groups['webservers'] or
      inventory_hostname in groups['loadbalancer']
  ufw:
    rule: deny
    to_port: 22
    proto: tcp

- name: Allow HTTP from load balancer on webservers
  when:
    - inventory_hostname in groups['webservers']
  ufw:
    rule: allow
    from_ip: 54.202.28.125
    port: 80
    proto: tcp

- name: Allow HTTP from anywhere for load balancer and Nagios
  when:
    - inventory_hostname in groups['loadbalancer'] or
      inventory_hostname in groups['nagios']
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow stats port for HAProxy
  when:
    - inventory_hostname in groups['loadbalancer']
  ufw:
    rule: allow
    port: 8404
    proto: tcp

- name: Allow NRPE
  ufw:
    rule: allow
    port: 5666
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
