- name: Allow SSH for users and Ansible from Nagios server
  ufw:
    rule: allow
    from_ip: 35.95.66.224
    to_port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 2222

- name: Deny all other SSH
  ufw:
    rule: deny
    to_port: 22
    proto: tcp

- name: Allow HTTP from load balancer and Nagios server
  ufw:
    rule: allow
    from_ip: "{{ item }}"
    port: 80
    proto: tcp
  loop:
    - 54.202.28.125
    - 35.95.66.224

- name: Allow NRPE
  ufw:
    rule: allow
    from_ip: 35.95.66.224
    port: 5666
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
